FROM openjdk:8-jdk-alpine
VOLUME [ "/tmp" ]
COPY target/SpringWebServiceUserService-0.0.1-SNAPSHOT.jar SpringWebServiceUserService.jar
COPY src/* src/
COPY pom.xml pom.xml
ENTRYPOINT [ "java", "-jar", "SpringWebServiceUserService.jar" ]