FROM openjdk:8-jdk-alpine
VOLUME [ "/tmp" ]
COPY target/SpringWebServiceDiscoveryService-0.0.1-SNAPSHOT.jar SpringWebServiceDiscoveryService.jar
COPY src/* src/
COPY pom.xml pom.xml
ENTRYPOINT [ "java", "-jar", "SpringWebServiceDiscoveryService.jar" ]