FROM openjdk:8-jdk-alpine
VOLUME [ "/tmp" ]
COPY target/SpringWebServiceGatewayService-0.0.1-SNAPSHOT.jar SpringWebServiceGatewayService.jar
COPY src/* src/
COPY pom.xml pom.xml
COPY Filters-Example.txt Filters-Example.txt
COPY Predicate-Example.txt Predicate-Example.txt
ENTRYPOINT [ "java", "-jar", "SpringWebServiceGatewayService.jar" ]